[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    https://github.com/adafruit/Adafruit_SHTC3.git
    adafruit/Adafruit Unified Sensor@^1.1.13
