using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Goalz.Data.Migrations
{
    public partial class AddQuizQuestionAnswer : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Quizzes"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Questions"" (
    ""Id""          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""QuizId""      bigint NOT NULL REFERENCES ""Quizzes""(""Id"") ON DELETE CASCADE,
    ""QuestionTxt"" text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ""IX_Questions_QuizId"" ON ""Questions""(""QuizId"");");

            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""Answers"" (
    ""Id""         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""QuestionId"" bigint NOT NULL REFERENCES ""Questions""(""Id"") ON DELETE CASCADE,
    ""AnswerTxt""  text NOT NULL DEFAULT '',
    ""IsCorrect""  boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ""IX_Answers_QuestionId"" ON ""Answers""(""QuestionId"");");

            // Update Parties FK to reference Quizzes (it may not exist yet)
            migrationBuilder.Sql(@"
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'FK_Parties_Quizzes_QuizId'
  ) THEN
    ALTER TABLE ""Parties""
      ADD CONSTRAINT ""FK_Parties_Quizzes_QuizId""
      FOREIGN KEY (""QuizId"") REFERENCES ""Quizzes""(""Id"") ON DELETE SET NULL;
  END IF;
END $$;");

            // Update PartyGroupAnswers FK to reference Answers (may reference old Answer table)
            migrationBuilder.Sql(@"
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'FK_PartyGroupAnswers_Answer_AnswerId'
  ) THEN
    ALTER TABLE ""PartyGroupAnswers"" DROP CONSTRAINT ""FK_PartyGroupAnswers_Answer_AnswerId"";
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'FK_PartyGroupAnswers_Answers_AnswerId'
  ) THEN
    ALTER TABLE ""PartyGroupAnswers""
      ADD CONSTRAINT ""FK_PartyGroupAnswers_Answers_AnswerId""
      FOREIGN KEY (""AnswerId"") REFERENCES ""Answers""(""Id"") ON DELETE CASCADE;
  END IF;
END $$;");

            // Seed sustainability quiz
            migrationBuilder.Sql(@"
INSERT INTO ""Quizzes"" (""Id"") VALUES (1) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('""Quizzes""', 'Id'), GREATEST(1, MAX(""Id""))) FROM ""Quizzes"";");

            migrationBuilder.Sql(@"
INSERT INTO ""Questions"" (""Id"", ""QuizId"", ""QuestionTxt"") VALUES
(1,  1, 'Which gas do trees absorb during photosynthesis?'),
(2,  1, 'What is the main cause of soil erosion in arboretums?'),
(3,  1, 'Which of these is a renewable energy source?'),
(4,  1, 'What percentage of the Earth''s surface is covered by forests?'),
(5,  1, 'Which practice helps maintain biodiversity in an arboretum?'),
(6,  1, 'What is carbon sequestration?'),
(7,  1, 'Which insect is most important for pollinating plants?'),
(8,  1, 'What does invasive species mean?'),
(9,  1, 'Which of the following reduces water usage in gardens?'),
(10, 1, 'What is the role of decomposers in an ecosystem?')
ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('""Questions""', 'Id'), GREATEST(10, MAX(""Id""))) FROM ""Questions"";");

            migrationBuilder.Sql(@"
INSERT INTO ""Answers"" (""Id"", ""QuestionId"", ""AnswerTxt"", ""IsCorrect"") VALUES
(1,  1,  'Carbon dioxide (CO2)',                                true),
(2,  1,  'Oxygen (O2)',                                        false),
(3,  1,  'Nitrogen (N2)',                                      false),
(4,  1,  'Methane (CH4)',                                      false),
(5,  2,  'Heavy rainfall',                                     true),
(6,  2,  'Tree planting',                                      false),
(7,  2,  'Mulching',                                           false),
(8,  2,  'Composting',                                         false),
(9,  3,  'Solar energy',                                       true),
(10, 3,  'Coal',                                               false),
(11, 3,  'Natural gas',                                        false),
(12, 3,  'Petroleum',                                          false),
(13, 4,  'About 31%',                                          true),
(14, 4,  'About 10%',                                          false),
(15, 4,  'About 50%',                                          false),
(16, 4,  'About 65%',                                          false),
(17, 5,  'Planting native species',                            true),
(18, 5,  'Using pesticides broadly',                           false),
(19, 5,  'Removing all undergrowth',                           false),
(20, 5,  'Monoculture planting',                               false),
(21, 6,  'Capturing and storing CO2 in plants and soil',       true),
(22, 6,  'Burning fossil fuels',                               false),
(23, 6,  'Releasing carbon gases',                             false),
(24, 6,  'Filtering water',                                    false),
(25, 7,  'Bees',                                               true),
(26, 7,  'Earthworms',                                         false),
(27, 7,  'Ants',                                               false),
(28, 7,  'Beetles',                                            false),
(29, 8,  'A non-native species that harms the local ecosystem',true),
(30, 8,  'A species that is endangered',                       false),
(31, 8,  'A plant grown in an arboretum',                      false),
(32, 8,  'A species that only lives underground',              false),
(33, 9,  'Drip irrigation',                                    true),
(34, 9,  'Overhead sprinklers',                                false),
(35, 9,  'Daily hosing',                                       false),
(36, 9,  'Flood irrigation',                                   false),
(37, 10, 'Breaking down dead organic matter into nutrients',   true),
(38, 10, 'Producing oxygen',                                   false),
(39, 10, 'Pollinating flowers',                                false),
(40, 10, 'Controlling pests',                                  false)
ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('""Answers""', 'Id'), GREATEST(40, MAX(""Id""))) FROM ""Answers"";");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE ""PartyGroupAnswers"" DROP CONSTRAINT IF EXISTS ""FK_PartyGroupAnswers_Answers_AnswerId"";
ALTER TABLE ""Parties"" DROP CONSTRAINT IF EXISTS ""FK_Parties_Quizzes_QuizId"";
DROP TABLE IF EXISTS ""Answers"";
DROP TABLE IF EXISTS ""Questions"";
DROP TABLE IF EXISTS ""Quizzes"";");
        }
    }
}
